# Generated by Django 5.2.1 on 2025-12-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('car_type', models.CharField(max_length=50)),
                ('service', models.CharField(choices=[('Basic Wash', 'Basic Wash'), ('Full Wash', 'Full Wash'), ('Interior Cleaning', 'Interior Cleaning'), ('Engine Wash', 'Engine Wash')], max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
